### ISSUE TITLE
Vulnerable to XSS 

### ISSUE THREAD

**Issue by Dani3lSun** [farzadso/ApexNoti--Oracle-APEX-Browser-Notifications#1]
Hi @farzadso 
just to let you know, please be sure to escape your inputs correctly to reduce Security Problems like XSS...
If Notification Title or Body comes from a Hidden Item which is set from DB you´ll never know what "bad" Users type in :)
I suggest you to use apex_escape.html to escape all inputs (title, body, ...).
You can test the security vulnerability by yourself, just insert this as title:
```
"); alert("XSS Test"); console.log("
```
Then you will see an alert popping up...

Ah and btw: Ff you export with APEX 5.1 the plugin export file is only compatible with other 5.1 and above instances...

Great to see the APEX Plugin community is growing that fast!;)

Best wishes
Daniel

**Comment by farzadso** [comment]
Hi Daniel,
@Dani3lSun 
Thanks for the heads up. As you already know, writing a plugin is a lengthy and time-consuming process and mixing it with daily activities causes such faults to occur. To be honest, I had jotted down a task to add the escaping code to the plugin but I got too carried away and forgot to. This will be added asap.

About the compatibility issue, what do you suggest? Do you suggest I created the plugin on an APEX 5.0.x instance and then export it?

**Comment by Dani3lSun** [comment]
Hi @farzadso 
yep I´m familiar with this, some time I decided to create simple templates for the most used plugins, like Item, Region and DA. This templates already include sample code for escaping, so it´s harder to forget it! :) But it is not that worse, just wanted to let you know...

Unfortunately there is no other way as using a real 5.0 instance some where, I also let one 5.0 instance run on my server, would be happy to upgrade it...
A feature like the Application Compatibility Mode would be nice, so a Dev can decide for which Version he wants to export it, but this is not possible right now...
As of now 5.0 support is important, but maybe in a couple of months, most Servers are hopefully on 5.1 and a Plugin Dev can gently un-support "old" APEX Versions :)

**Comment by farzadso** [comment]
I added the XSS prevention counter-measure Daniel. 
Is there any chance you could share those templates? Would be a big help.

In the upcoming days i'll try to replicate a copy on a 5.0 server on a new PDB and get full compatibility.

Even if the compatibility mode got applied on the plugin too, it would've been nice.

I truly appreciate your feedback :+1:

**Comment by farzadso** [comment]
I added a version called "dynamic_action_plugin_com_jafr_apexnoti_4.2.sql" in the master branch. It supports APEX 4.2+

**Comment by Dani3lSun** [comment]
Hey @farzadso 

thanks for the fast update!;)
The plugin templates are still here on Github:
https://github.com/Dani3lSun/apex-plugin-templates
Updated just now the old "sys.htf.escape_sc" with "apex_escape.html" to be up2date!

**Comment by farzadso** [comment]
Cheers.

Actually I thank YOU for being so thorough and going through my code to find flaws.

Thanks for the link too. Just downloaded them all.

Let's just keep our fingers crossed that the apex_escape.html function doesn't get deprecated :1st_place_medal:
